cmake_minimum_required(VERSION 4.0)
project(lab16)

set(CMAKE_CXX_STANDARD 20)

add_executable(lab16 main.cpp
        menu.h
        menu.cpp
        utils.h
        utils.cpp
        tnode.h
        binarytree.h
        binarytree.cpp
        treechecker.h
        treechecker.cpp
        treeinput.h
        treeinput.cpp
        treework1.h
        treework1.cpp
        treework14.h
        treework14.cpp
        treework17.h
        treework17.cpp)
