cmake_minimum_required(VERSION 4.0)
project(lab21)

set(CMAKE_CXX_STANDARD 20)

add_executable(lab21 main.cpp
        menu.h
        menu.cpp
        utils.h
        utils.cpp
        graph.h
        graph.cpp
        graf1.h
        graf1.cpp
        graf4.h
        graf4.cpp
        graf8.h
        graf8.cpp)
