cmake_minimum_required(VERSION 4.0)
project(lab13)

set(CMAKE_CXX_STANDARD 20)

add_executable(lab13 main.cpp
        menu.h
        menu.cpp
        utils.h
        utils.cpp
        stlprint.h
        stl3alg6.h
        stl3alg6.cpp
        stl3alg16.h
        stl3alg16.cpp
        stl3alg36.h
        stl3alg36.cpp
        stl3alg60.h
        stl3alg60.cpp)
