cmake_minimum_required(VERSION 4.0)
project(lab15)

set(CMAKE_CXX_STANDARD 20)

add_executable(lab15 main.cpp
        menu.h
        menu.cpp
        utils.h
        utils.cpp
        point.h
        point.cpp
        line.h
        line.cpp
        dependentline.h
        dependentline.cpp
        student.h
        student.cpp
        task1.h
        task1.cpp
        task2.h
        task2.cpp
        task3.h
        task3.cpp
        task4.h
        task4.cpp
        task5.h
        task5.cpp)
