cmake_minimum_required(VERSION 4.0)
project(lab14)

set(CMAKE_CXX_STANDARD 20)

add_executable(lab14 main.cpp
        menu.h
        menu.cpp
        utils.h
        utils.cpp
        stl5assoc2.h
        stl5assoc2.cpp
        stl5assoc17.h
        stl5assoc17.cpp
        stl5assoc21.h
        stl5assoc21.cpp)
