cmake_minimum_required(VERSION 4.0)
project(lab10)

set(CMAKE_CXX_STANDARD 20)

add_executable(lab10 main.cpp
        menu.h
        menu.cpp
        utils.h
        utils.cpp
        nodes.h
        nodeio.h
        nodeio.cpp
        stack.h
        stack.cpp
        queue.h
        queue.cpp
        list.h
        list.cpp
        dynamic3.h
        dynamic3.cpp
        dynamic24.h
        dynamic24.cpp
        listwork1.h
        listwork1.cpp
        listwork22.h
        listwork22.cpp
        listwork59.h
        listwork59.cpp)
